title: Hane's Portfolio
logo: /assets/img/logo.png
theme: jekyll-theme-minimal
description: >
路路Hello, test description \n
路路with some "quotes" of various 'types',\n
路路and also a blank line:\n
路路\n
Welcome!  Im Hane and Im glad you dropped by.\n
I am currently a Senior Consultant @ IBM, with past work experience in Tech, Sales, and Finance.  \n
My main superpower is the ability to empathize and understand the needs of my client/customer. Using this, I identify their key problems and build solutions that can bridge the gaps.
Im always opened to meeting new people, and learning new things. Lets connect!
